"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, samples.py, metrics.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures an E2E continued-pre-training workflow: the pinned BERT-Base uncased snapshot is
digest-verified and loaded, a digest-pinned real corpus (SciTLDR paper abstracts) is fetched, validated and
split, both inference contracts are exercised, the frozen model's masked-token metrics on held-out abstracts
are read beside a unigram floor, a bounded masked-language-model fine-tuning of the last encoder layers adapts
the model to the domain in the kernel, the held-out split is scored again, and the adapter is exported and
reloaded.

Review fixes (Notebook Review Framework v1, review PR #8, MLM-M1..M4 / MLM-m1..m5): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart), every re-run of Sections 5-7 starts from the pretrained
model, BYOD limits are checked in Section 4 before any model call, and the guided layer (how to use, roadmap,
predictions, worked answers, a change-one-thing activity, troubleshooting, glossary, conclusion) is added.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "bert_masked_lm_pipeline",
    "repo_name": "bert-masked-lm-pipeline",
    "stem": "bert_masked_lm",
    "notebook_name": "bert_masked_lm_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt` (the pins equal those of the sibling BART
    # pipelines, whose lock this is byte for byte).
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned BERT-Base uncased snapshot (safetensors, 440 MB), fetches the three digest-pinned SciTLDR-A files from the "
        "project repository (5.5 MB, no credential), reads the paper abstracts and draws 300 / 50 / 100 training, validation "
        "and test documents from the release's own paper-disjoint members, fills one mask in an unseen abstract's opening "
        "sentence and embeds two test abstracts through the inference contracts with an input manifest and a rejection "
        "probe, scores the frozen model on the test abstracts by masked-token perplexity and top-1 / top-5 accuracy at "
        "seeded masks beside the add-one unigram floor, runs a bounded continued masked-language-model training of the "
        "last four encoder layers with validation-perplexity epoch selection, scores the held-out split again, fills "
        "the same masks and re-embeds the same abstracts with the adapted model, exports the adapter as safetensors with a "
        "manifest, and reloads that artifact into a fresh pipeline to verify parity. The default path needs no repository "
        "clone, no DIMER worker or service, no credential, no upload dialog and no configuration edit (NOTEBOOK_SPEC 2.2 "
        "§5). A CUDA runtime is used automatically when present. Measured times come from runs of the previous notebook "
        "version, whose model stages are the same: the Kaggle Tesla T4 run of 2026-09-19 took 272.5 s for all cells "
        "including the 447 MB checkpoint download, and a local Windows CPU pre-flight took 233.1 s with the files "
        "pre-staged (207 s of it the two-epoch adaptation). No hosted CPU run is recorded, so on a hosted CPU runtime "
        "expect roughly the CPU pre-flight figure (an estimate). Building the isolated environment and downloading the "
        "checkpoint come on top of these."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over). Supply your own text corpus through the upload dialog on Colab or a "
        "file path in `BYOD_PATH` on any runtime, as a CSV (columns `id`, `text`), a JSON array or JSONL file of "
        "`{id, text}` records, or a plain `.txt` file in which every blank-line-separated paragraph is one document. It "
        "needs at least **12 distinct documents** (so the split leaves 8 training, 2 validation and 2 test documents), each "
        "at most 512 WordPiece tokens; Section 4 checks both, names the split or record it refuses, and reports how many "
        "duplicate texts it dropped, before any model runs. It passes through the same validation, "
        "seeded text-disjoint split, unigram floor, frozen scoring, fine-tuning, held-out evaluation, cloze and embedding "
        "checks, artifact export and reload-parity cells as the SciTLDR sample. The expected schema and the ceilings are "
        "stated in the Prerequisites and in Section 4, and uploaded files stay inside this runtime. BYOD is optional and "
        "never part of the default path."
    ),
    "pipeline_class": "BERTMaskedLMPipeline",
    "weights_key": "bert-base-uncased",
    "modules": ["pipeline.py", "samples.py", "metrics.py"],
    "entry_module": "pipeline.py",
    "identity_names": {},
    "runtime_imports": ["torch", "transformers"],
    "title": "BERT-Base uncased — DIMER E2E continued-pre-training tutorial: masked-token prediction on paper abstracts (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/bert-masked-lm-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/bert-masked-lm-pipeline/blob/main/tutorials/bert_masked_lm_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-google--bert%2Fbert--base--uncased-ffcc4d?style=flat",
            "https://huggingface.co/google-bert/bert-base-uncased",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-google--research%2Fbert-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/google-research/bert",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-1810.04805-b31b1b.svg", "https://arxiv.org/abs/1810.04805"),
    ],
    "capability": "masked-language modelling (fill-mask: ranked candidates for one `[MASK]`), sentence embeddings (768-d, CLS or mean pooled, L2-normalised) and bounded continued masked-language-model training of the last encoder layers on a text corpus, measured by held-out masked-token perplexity and top-k accuracy, using the pinned BERT-Base uncased weights",
    "intro": (
        "At inference the WordPiece tokenizer lower-cases the text and one forward pass of the 12-layer bidirectional "
        "encoder runs; `fill_mask` reads the output-vocabulary logits at the single `[MASK]` position through the "
        "masked-LM head and ranks them by a softmax over the 30,522-token vocabulary, while `embed` takes the encoder's "
        "last hidden states and pools them to one 768-d vector per text (the `[CLS]` position, or the attention-masked "
        "mean) and L2-normalises it. The carried pipeline module adds manifest verification, input validation and "
        "ceilings (over-long texts are rejected, not truncated), the two task methods and fixed output contracts. **The "
        "fill-mask `score` is not a calibrated probability** (it is a softmax ranking signal), and **embeddings are "
        "representations, not predictions**; the pipeline ships no threshold for either.\n\n"
        "What this notebook adds to inference is **continued pre-training measured by the model's own objective**. The "
        "dataset is real: SciTLDR-A (Cachola et al., 2020; Apache-2.0) ships the abstracts of 3,229 computer-science "
        "papers as three digest-pinned JSON-Lines files fetched from the project repository at a pinned commit; only the "
        "abstract text is used, so every record is one document and no label is needed. The carried `metrics.py` masks a "
        "**seeded 15 %** of each held-out abstract's WordPiece tokens — the same positions for every model scored under "
        "the same seed — and reads the negative log-likelihood and the rank of the original token at every masked "
        "position, aggregated into **masked perplexity**, **bits per masked token** and **top-1 / top-5 accuracy**; an "
        "**add-one unigram model** fitted on the training tokens is the floor a model that ignores context reaches. The "
        "fine-tuning question is whether a bounded masked-language-model adaptation of the last encoder layers on 300 "
        "abstracts lowers that perplexity on abstracts the model has not seen. Nothing here is a quality claim: a lower "
        "masked perplexity says the adapted encoder predicts missing words of paper abstracts better, not that its "
        "embeddings are better for your task.\n\n"
        "**Who this is for.** A learner who knows basic Python and has met the idea of a language model, and wants to see "
        "how a pretrained encoder is measured and adapted to a new kind of text. No prior experience with BERT, perplexity "
        "or fine-tuning is assumed; each term is explained where it is first used and again in the **Glossary** at the end.\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Fill-mask | Embedding | Continued pre-training |\n"
        "|---|---|---|---|\n"
        "| Input | one text with exactly one `[MASK]` | 1..64 texts | 300 training abstracts (no labels) |\n"
        "| Model | BERT-Base uncased encoder + masked-LM head | the same encoder, pooled | the last 4 encoder layers trained on masked words |\n"
        "| Output | the top-`k` candidate tokens with softmax scores | one unit-length 768-d vector per text | an adapter (safetensors) and held-out masked perplexity / top-k accuracy |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — the isolated environment, the carried code and the model verification — and "
        "can be run without study. The learning path starts in Section 4. Form fields (`# @param`) are the only values "
        "meant to be edited; the defaults reproduce the recorded path. Each stage states what it does, asks you to "
        "**predict** before it runs, and the next cell opens with **What to notice** and a collapsible **Check your "
        "reasoning** block with a worked answer. Each optional experiment names the cell to change and the cells to "
        "re-run. Section 10 is a **change-one-thing activity**. **Troubleshooting**, a **Glossary** and a **Conclusion** "
        "template are at the end. Your notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the corpus → 5 fill a mask and embed with the pretrained model → 6 the "
        "unigram floor and the pretrained model's masked perplexity → 7 continue pre-training the last four layers → 8 "
        "compare on held-out abstracts → 9 clozes and embeddings before and after, export and reload → 10 **change one "
        "thing: fewer trainable layers** → conclude."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *text with one `[MASK]` → encoder and masked-LM head → ranked "
        "candidate tokens* and *texts → encoder → unit vectors*, and say why the fill-mask score is not a probability of "
        "being right (Section 5); (2) explain, from Section 6's numbers, why the unigram floor's masked perplexity is in "
        "the thousands while the pretrained model's is near 15; (3) predict and then check how much a bounded continued "
        "pre-training of the last encoder layers lowers masked perplexity on held-out abstracts (Sections 7–8); (4) "
        "explain why validation, never test, chooses the kept epoch; (5) predict and then measure how the gain changes "
        "with one trainable layer instead of four (Section 10); (6) state what a lower masked perplexity does and does not "
        "tell you about the embeddings and clozes of Section 9; and (7) check that an exported adapter reproduces the "
        "evaluated model (reload parity, Section 9)."
    ),
    "exclusions": (
        "classification or other supervised heads, next-sentence prediction, multi-mask filling, raw-logit access, text "
        "generation (BERT is an encoder), cased or non-English text (the checkpoint is uncased English), contrastively "
        "trained sentence similarity (the `qwen3-embedding-pipeline` sibling covers retrieval-grade embeddings), "
        "full-model or embedding-table training, any similarity or downstream-task score, and any claim that a SciTLDR "
        "abstract split stands in for your corpus. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and Colab or Jupyter familiarity; no prior experience with BERT or fine-tuning. The notebook explains masked-language modelling, the softmax over a vocabulary (and why it is not a calibrated probability), perplexity (the exponential of the mean negative log-likelihood, an intrinsic number, not a judgement of embedding quality) and cosine similarity between unit vectors where they are first used; the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter, and a Windows or macOS kernel is not supported (Section 1 stops with that message). The default path runs on CPU (float32) and uses CUDA automatically when available. The locked install (PyTorch 2.14.0 with its CUDA libraries) and the 440 MB checkpoint are the large downloads. Measured on the previous notebook version, whose model stages are the same, in a local Windows CPU pre-flight (2026-09-19, float32): 6.6 s to score the 100-abstract test split (2,983 masked positions) and 206.9 s for the two-epoch adaptation over 300 abstracts with a 50-abstract validation pass per epoch (about 100 s per epoch); the whole Kaggle Tesla T4 run took 272.5 s including the checkpoint download. No hosted CPU run is recorded; expect roughly the CPU pre-flight figures there (an estimate).",
        "- **Data contract:** records are `{id, text}` — one document of the domain, 1..4,000 characters and at most 512 WordPiece tokens including `[CLS]`/`[SEP]` (a longer record is refused, not truncated, everywhere), ids matching `[A-Za-z0-9_.:-]{1,64}` and unique; a dataset holds at most 20,000 records; texts are de-duplicated case-insensitively before splitting so the same document never sits in two splits; text is lower-cased by the tokenizer, so case carries no information. BYOD accepts CSV, JSON, JSONL or TXT in that shape and needs at least **12 distinct documents**: the seeded split keeps about 20 % for test and 15 % for validation, and must leave at least 8 training, 2 validation and 2 test documents. Section 4 checks this and the 512-token ceiling before any model runs, and names the split or the record (by split and id) it refuses.",
        "- **Validation is structural, not semantic:** nothing checks that a record belongs to the domain you mean — an off-topic corpus is trained on without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — an internal document collection is exactly that. The default path uploads nothing.",
        "- **External access (data):** besides the Hub, the default path fetches three pinned objects (`train.jsonl` 3,155,015 bytes, `dev.jsonl` 1,124,865 bytes, `test.jsonl` 1,204,107 bytes; SHA-256 `b222771d…` / `3191fa98…` / `fb42dd6c…`) from `raw.githubusercontent.com` at the pinned `allenai/scitldr` commit over HTTPS, each refused on any mismatch before it is read; SciTLDR is Apache-2.0 (Cachola et al., 2020).",
    ],
    "cells": [
        {
            "md": (
                "## 4. Referenced corpus, validation and split\n\n"
                "`fetch_corpus` downloads the three pinned SciTLDR-A files (or reads them from the cache), refuses a "
                "byte-size or SHA-256 mismatch per file before it is parsed, and `read_corpus` flattens each JSON-Lines "
                "member into records whose `text` is the abstract's sentences joined by a space — titles and TLDRs are "
                "left unread. `build_sample_dataset` keeps abstracts of 200..2,000 characters, drops repeated texts, and "
                "draws 300 training documents from the `train` member, 50 validation documents from `dev` and 100 test "
                "documents from `test` by a seeded shuffle — the release's own paper-disjoint partition. `validate_dataset` "
                "then checks every record against the contract, `check_split_disjoint` asserts no text appears in two "
                "splits, and the training split is written to `outputs/{stem}_train.csv` in the shape BYOD expects.\n\n"
                "The cell also checks two things the model would otherwise only discover later, using the tokenizer and "
                "plain text only (no model call): every record's WordPiece count against the 512-token ceiling (a longer "
                "record is refused by split and id), and the **cloze** records Section 5 masks — the opening sentence of a "
                "record with its longest word of four or more letters replaced by `[MASK]`. With the sample these are "
                "three dev abstracts outside every split (*unseen*); a record whose opening sentence has no such word is "
                "skipped.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a file already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. `split_dataset` de-duplicates texts and makes a seeded 65 / 15 / 20 % split; it refuses a "
                "corpus that leaves fewer than 8 training, 2 validation or 2 test documents (at least 12 distinct "
                "documents), naming the split. Under BYOD there is no pool of unused documents, so the clozes come from "
                "your **test** records and are labelled that way (`byod-test-…`).\n\n"
                "Look for: 1,992 + 619 + 618 raw papers, three digests, splits 300 / 50 / 100, the longest record's token "
                "count, three cloze records, and four refusal probes — a duplicate id, an empty text, a missing field and "
                "a dataset too small to split — each rejected before `torch` does anything.\n\n"
                "**Predict before running:** the sample keeps abstracts of 200..2,000 characters. Will any of them come "
                "near the 512-token ceiling?"
            ),
            "code": (
                "import hashlib\n"
                "import io\n"
                "import json\n"
                "import re\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "dropped_duplicates = 0\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_path = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_path.is_file():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} is not a file in this runtime: fix the path, or leave BYOD_PATH empty to upload a file in Colab.')\n"
                "        file_name = byod_path.name\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the file in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise RuntimeError(f'Upload exactly one .csv, .json, .jsonl or .txt file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a file already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_path = Path('work') / Path(file_name).name\n"
                "        byod_path.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_path.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_path)\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED)\n"
                "    dropped_duplicates = len(records) - sum(len(part) for part in splits.values())\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_papers = {{'byod': len(records)}}\n"
                "else:\n"
                "    corpus = read_corpus(fetch_corpus(cache_dir='weights/scitldr'))\n"
                "    raw_papers = {{name: len(part) for name, part in corpus.items()}}\n"
                "    splits = build_sample_dataset(corpus, seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}} ({{CORPUS_RELEASE}}; {{CORPUS_LICENSE}})'\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=MIN_RECORDS if name == 'train' else 1) for name, part in splits.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "# Every record against the WordPiece ceiling, with the tokenizer only (no model call).\n"
                "token_budget = check_byod_tokens(splits, pipe.count_tokens, max_tokens=MAX_TEXT_TOKENS)\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "print({{'data_source': data_source, 'raw_papers': raw_papers, 'splits': disjoint, 'file_sha256': {{k: v[2][:12] + '...' for k, v in CORPUS_FILES.items()}}}})\n"
                "print({{'token_budget': token_budget, 'duplicate_texts_dropped': dropped_duplicates}})\n\n"
                "def cloze_of(record):\n"
                "    \"\"\"The opening sentence with its longest alphabetic word (4+ letters) replaced by [MASK]: (cloze, gold word), or None if it has no such word.\"\"\"\n"
                "    sentence = record['text'].split('. ')[0]\n"
                "    words = [w for w in re.findall(r'[A-Za-z]+', sentence) if len(w) >= 4]\n"
                "    if not words:\n"
                "        return None\n"
                "    gold = max(words, key=len)\n"
                "    cloze = re.sub(r'\\b' + gold + r'\\b', MASK_TOKEN, sentence, count=1)\n"
                "    return (cloze, gold.lower()) if cloze.count(MASK_TOKEN) == 1 else None\n\n"
                "if USE_BYOD:\n"
                "    cloze_pool, cloze_prefix = test_records[2:] + test_records[:2], 'byod-test'\n"
                "    cloze_source = 'BYOD test records (scored in Sections 6 and 8; not unseen documents)'\n"
                "else:\n"
                "    used = {{r['text'].lower() for part in splits.values() for r in part}}\n"
                "    cloze_pool, cloze_prefix = [r for r in filter_records(corpus['dev']) if r['text'].lower() not in used], 'unseen'\n"
                "    cloze_source = 'unseen SciTLDR dev abstracts (in none of the splits)'\n"
                "chosen, skipped_clozes = [], 0\n"
                "for record in cloze_pool:\n"
                "    made = cloze_of(record)\n"
                "    if made is None:\n"
                "        skipped_clozes += 1\n"
                "        continue\n"
                "    chosen.append((record, made))\n"
                "    if len(chosen) == 3:\n"
                "        break\n"
                "if not chosen:\n"
                "    raise ValueError('No test record opens with a sentence that has a word of four or more letters, so Section 5 has no cloze to fill. Start at least one document with an ordinary sentence ending in \". \", then run this cell again.')\n"
                "unseen_records = [{{**r, 'id': f'{{cloze_prefix}}-{{i:02d}}'}} for i, (r, _made) in enumerate(chosen)]\n"
                "clozes = {{r['id']: made for r, (_record, made) in zip(unseen_records, chosen, strict=True)}}\n"
                "print({{'clozes': len(clozes), 'cloze_source': cloze_source, 'records_skipped_without_a_usable_word': skipped_clozes}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'unique_texts': manifest['unique_texts'], 'text_chars': manifest['text_chars'], 'total_chars': manifest['total_chars'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "print({{'example': {{'id': train_records[0]['id'], 'text': train_records[0]['text'][:200] + '...'}}}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in train_records[:8]],\n"
                "    'empty text': [{{**train_records[0], 'text': '   '}}, *train_records[1:8]],\n"
                "    'missing field': [{{'id': r['id']}} for r in train_records[:8]],\n"
                "    'too small': train_records[:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the longest record's token count against the 512-token ceiling, and that the splits "
                "share no text.\n\n"
                "<details><summary>Check your reasoning</summary>No: in a local Windows CPU check of this notebook version "
                "the longest of the 450 sample records had 411 WordPiece tokens, so the ceiling is never reached (2,000 "
                "characters of English prose is roughly 400–450 tokens). A BYOD document of a few thousand words would exceed it and is refused here, by split and "
                "id, instead of failing in Section 6.</details>\n\n"
                "## 5. Fill a mask and embed through the inference contracts\n\n"
                "Before any adaptation, both inference contracts are exercised as they always were. The first **cloze** "
                "chosen in Section 4 is filled — the removed word is the *gold* word, which may be several WordPiece "
                "tokens, in which case no single candidate can match it (reported, never asserted). With the sample the "
                "clozes come from unseen abstracts; under BYOD they are your test records, and the ids say so. "
                "`validate_inputs` applies exactly the checks "
                "`fill_mask` and `embed` apply (text type and character ceiling, exactly one `[MASK]` for the cloze, "
                "`top_k` and `pooling` within their contracts) and returns an input manifest; the WordPiece ceiling "
                "`MAX_TEXT_TOKENS` (512) needs the real tokenizer and is enforced inside the pipeline, which **rejects, "
                "never truncates**. A two-mask input is validated too and its rejection recorded as a finding. `fill_mask` "
                "returns `top_k` candidates with a softmax `score` (a ranking signal, not a calibrated probability); "
                "`embed` returns one unit-norm 768-d vector per text under the requested pooling. The clozes and the "
                "embeddings of two test abstracts are kept as the *before* column for Section 9.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, "
                "Section 6 or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it "
                "first reloads the pretrained model from the verified snapshot with `reset_to_pretrained()`, so a "
                "*before* or *frozen* number is never read from the adapted model.\n\n"
                "**Predict before running:** for the masked word in the printed cloze, will the gold word be among the "
                "five candidates? Will the two abstracts' cosine be close to 0 or close to 1?"
            ),
            "code": (
                "import gc\n"
                "import time\n\n"
                "TOP_K = 5  # @param {{type:\"integer\"}}\n"
                "POOLING = 'mean'  # @param [\"cls\", \"mean\"]\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = BERTMaskedLMPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n"
                "reset_to_pretrained()\n"
                "cloze, gold = clozes[unseen_records[0]['id']]\n"
                "pair_texts = [test_records[0]['text'], test_records[1]['text']]\n"
                "ceilings = {{'MAX_TEXT_CHARS': MAX_TEXT_CHARS, 'MAX_TEXT_TOKENS': MAX_TEXT_TOKENS, 'MAX_BATCH': MAX_BATCH, 'MAX_TOP_K': MAX_TOP_K, 'VOCAB_SIZE': VOCAB_SIZE, 'HIDDEN_SIZE': HIDDEN_SIZE, 'MASK_TOKEN': MASK_TOKEN, 'MASK_TOKEN_ID': MASK_TOKEN_ID, 'POOLINGS': POOLINGS, 'DEFAULT_TOP_K': DEFAULT_TOP_K}}\n"
                "print(ceilings)\n"
                "input_manifest = validate_inputs([cloze, *pair_texts], top_k=TOP_K, pooling=POOLING, names=['cloze', 'pair-a', 'pair-b'])\n"
                "try:\n"
                "    validate_inputs([f'A {{MASK_TOKEN}} and another {{MASK_TOKEN}}.'], top_k=TOP_K, pooling=POOLING)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'two-mask-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "started = time.perf_counter()\n"
                "filled = pipe.fill_mask(cloze, top_k=TOP_K)\n"
                "fill_seconds = round(time.perf_counter() - started, 3)\n"
                "started = time.perf_counter()\n"
                "embedding_result = pipe.embed(pair_texts, pooling=POOLING)\n"
                "embed_seconds = round(time.perf_counter() - started, 3)\n"
                "vectors = np.asarray(embedding_result['embeddings'], dtype=np.float32)\n"
                "scores = [c['score'] for c in filled['candidates']]\n"
                "checks = {{\n"
                "    'top_k_candidates_returned': len(filled['candidates']) == TOP_K,\n"
                "    'scores_descending_in_unit_interval': all(a >= b for a, b in zip(scores, scores[1:], strict=False)) and all(0.0 < s <= 1.0 for s in scores),\n"
                "    'tokens_within_vocab': all(0 <= c['token_id'] < VOCAB_SIZE for c in filled['candidates']),\n"
                "    'n_tokens_within_ceiling': 1 <= filled['n_tokens'] <= MAX_TEXT_TOKENS and all(1 <= n <= MAX_TEXT_TOKENS for n in embedding_result['n_tokens']),\n"
                "    'one_unit_vector_per_text': vectors.shape == (2, HIDDEN_SIZE) and bool(np.allclose(np.linalg.norm(vectors, axis=1), 1.0, atol=1e-4)),\n"
                "    'pooling_as_requested': embedding_result['pooling'] == POOLING and embedding_result['dim'] == HIDDEN_SIZE,\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'inference output failed a sanity check: {{checks}}')\n"
                "print({{'cloze': cloze, 'gold_word': gold, 'candidates': [(c['token'], round(c['score'], 4)) for c in filled['candidates']], 'gold_in_top_k': gold in [c['token'] for c in filled['candidates']], 'seconds': fill_seconds}})\n"
                "print({{'pair_cosine': round(float(vectors[0] @ vectors[1]), 4), 'pooling': POOLING, 'n_tokens': embedding_result['n_tokens'], 'seconds': embed_seconds, 'checks': checks, 'findings': len(input_manifest['findings']), 'score_semantics': 'softmax ranking signal, not a calibrated probability; no threshold shipped'}})\n"
                "before = {{rid: [c['token'] for c in pipe.fill_mask(text, top_k=TOP_K)['candidates']] for rid, (text, _gold) in clozes.items()}}\n"
                "vectors_before = vectors\n"
                "print({{'clozes_filled_by_the_frozen_model': len(before), 'cloze_source': cloze_source}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the five candidates are all plausible words for the slot even when the gold word is "
                "missing, and the scores fall quickly after the first.\n\n"
                "<details><summary>Check your reasoning</summary>In the recorded CPU pre-flight of the previous notebook "
                "version and in a local Windows CPU check of this one, the first cloze's gold word was `problems` and the pretrained top five were `systems situations "
                "phenomena events objects`: grammatical, on-topic, and wrong. The score is a softmax over 30,522 tokens, "
                "a ranking signal rather than a probability of being right: the top candidate scored only 0.107 there, and "
                "even a high score would not mean that chance of being correct. Mean-pooled embeddings of two abstracts from one field are usually close to 1 (0.86 for this "
                "pair in that run): cosine between BERT vectors is high for almost any two English texts, which is one "
                "reason the notebook calls embeddings representations, not judgements of similarity.</details>\n\n"
                "## 6. The unigram floor and the frozen model's masked-token metrics on the test split\n\n"
                "Two numbers frame the adaptation. `pipe.unigram_baseline` fits an add-one-smoothed unigram model over the "
                "30,522-token vocabulary on the training tokens and predicts every masked position of the test abstracts "
                "with it: the perplexity and top-k accuracy a model that knows the domain's word frequencies but ignores "
                "every context reaches — expect a perplexity in the thousands and a top-1 accuracy of a few percent (the "
                "commonest tokens). `pipe.evaluate` masks a seeded 15 % of each test abstract's interior WordPiece tokens "
                "(`record_seed` makes the positions a function of the record id and `SEED`, so every model scored here "
                "sees the same masks), runs the frozen encoder and masked-LM head once per record, and reads the "
                "negative log-likelihood and the rank of the original token at every masked position: **masked "
                "perplexity** (`exp` of the mean NLL), **bits per masked token** and **top-1 / top-5 accuracy**. Records "
                "over `MAX_TEXT_TOKENS` are refused, never truncated (Section 4 already checked). The cell reloads the "
                "pretrained model first if an earlier pass adapted it, and refuses to report an adapted model as frozen. "
                "Scoring the 100 test abstracts took 6.6 s in the local CPU pre-flight of the previous notebook version.\n\n"
                "**Predict before running:** roughly what masked perplexity will a model that ignores context entirely "
                "(the unigram floor) reach — tens, hundreds or thousands? And the pretrained model?"
            ),
            "code": (
                "SEED = 0  # @param {{type:\"integer\"}}\n"
                "MASK_RATE = 0.15  # @param {{type:\"number\"}}\n\n"
                "def brief(m):\n"
                "    return {{'perplexity': round(m['perplexity'], 2), 'bits_per_token': round(m['bits_per_token'], 3), 'top1_accuracy': round(m['top1_accuracy'], 4), 'top5_accuracy': round(m['top5_accuracy'], 4), 'n_masked': m['n_masked']}}\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "unigram = pipe.unigram_baseline(train_records, test_records, mask_rate=MASK_RATE, seed=SEED)\n"
                "print({{'unigram_floor': brief(unigram), 'baseline': unigram['baseline'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, mask_rate=MASK_RATE, seed=SEED)\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "if frozen_test['n_masked'] != unigram['n_masked']:\n"
                "    raise RuntimeError(f\"The floor and the frozen model were scored at different masked positions ({{unigram['n_masked']}} vs {{frozen_test['n_masked']}}); re-run this cell without changing SEED or MASK_RATE in between.\")\n"
                "print({{'frozen_model_test': brief(frozen_test), 'n_records': frozen_test['n_records'], 'verdict': frozen_test['verdict'], 'adapted': frozen_test['adapted'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'frozen_below_unigram_floor': frozen_test['perplexity'] < unigram['perplexity']}})\n"
                "print({{'definitions': frozen_test['definitions']}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the gap between the floor and the pretrained model, and `adapted: False`.\n\n"
                "<details><summary>Check your reasoning</summary>Thousands for the floor: in the recorded runs of the "
                "previous notebook version (same model, data and seed) the unigram floor scored a masked perplexity of "
                "about 1,175 with top-1 accuracy 4.2 %, and the pretrained model about 15.09 with top-1 53.3 % (Kaggle T4 "
                "and the CPU pre-flight agree). A perplexity of 1,175 means the floor is, on average, as unsure as a "
                "uniform choice among about 1,175 tokens: knowing only how frequent words are, it can guess `the` and "
                "`of` but nothing that depends on the sentence. The pretrained encoder reads the words on both sides of "
                "each gap, which narrows the choice to about 15 equally likely tokens — BooksCorpus and Wikipedia already "
                "contain a lot of technical prose.</details>\n\n"
                "## 7. Bounded continued masked-language-model training\n\n"
                "`pipe.adapt` trains only the last `TRAINABLE_LAYERS` encoder layers — four by default, "
                "28,351,488 of 109,514,298 parameters; the word, position and token-type embeddings, the earlier layers "
                "and the masked-LM head with its decoder tied to the word embeddings stay frozen — with the model's own "
                "pre-training objective: every epoch re-draws a seeded `MASK_RATE` of each training abstract's interior "
                "tokens, replaces them with `[MASK]` and applies cross-entropy at those positions only (100 % `[MASK]`, "
                "not the upstream 80/10/10 replacement mix), AdamW at a fixed learning rate, gradient clipping at 1.0, "
                "seeded shuffling and no scheduler. Epoch 0 records the frozen model's validation metrics under the "
                "evaluation masking; every epoch is scored the same way, and the epoch with the lowest validation masked "
                "perplexity is kept.\n\n"
                "Watch validation perplexity fall from about 13 by a point or two over two epochs while top-1 accuracy "
                "creeps up (about 100 s of training plus a validation pass per epoch in the local CPU pre-flight of the "
                "previous notebook version; much less on a GPU). That pre-flight's sweep on this sample (adapted test "
                "perplexity, local Windows CPU): two layers at 1e-4 reached 12.96, four layers at 1e-4 reached 12.51 and "
                "four layers at 5e-5 reached 12.59 in about the same time — the default keeps the standard 5e-5.\n\n"
                "**Adaptation always starts from the pretrained model.** If this cell runs again (for example with "
                "`TRAINABLE_LAYERS = 1` in Section 10), it first reloads the pretrained model from the verified snapshot, "
                "so the new training never stacks on the previous one, epoch 0 really is the frozen model, and the "
                "exported adapter holds exactly the layers this run trained; `pipe.adapt` itself refuses a model that is "
                "already adapted.\n\n"
                "**Predict before running:** will validation perplexity fall in both epochs? Which epoch will be kept?"
            ),
            "code": (
                "EPOCHS = 2  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 5e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 8  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_LAYERS = 4  # @param {{type:\"integer\"}}\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row['val_perplexity'] = round(entry['val']['perplexity'], 2)\n"
                "        row['val_top1'] = round(entry['val']['top1_accuracy'], 4)\n"
                "        row['val_top5'] = round(entry['val']['top5_accuracy'], 4)\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_layers=TRAINABLE_LAYERS, mask_rate=MASK_RATE, seed=SEED, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'objective': adapt_result['objective'], 'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'train_tokens': adapt_result['n_train_tokens'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, and the kept epoch is the one with the lowest "
                "validation perplexity — the test split plays no part in that choice.\n\n"
                "<details><summary>Check your reasoning</summary>In the local CPU pre-flight of the previous notebook "
                "version validation perplexity went 12.89 → 11.15 → 10.87 over epochs 0, 1 and 2, so it fell in both "
                "epochs and epoch 2 was kept. It need not: with more epochs or a higher learning rate it can rise again, "
                "and the rule then keeps an earlier epoch (epoch 0 means no training change is kept). Choosing the epoch "
                "on the test split would make the Section 8 comparison optimistic, because the test abstracts would have "
                "helped pick the model they then judge.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test split was never used for training or epoch selection, and no abstract in it appears in the "
                "training or validation splits. The adapted model is scored exactly as the frozen model was in Section 6 "
                "— same masks, same seed — and the three rows are put side by side. Look for a masked perplexity a point "
                "or two below the frozen one with top-1 and top-5 accuracy up by about a point, all far from the unigram "
                "floor. The cell prints a verdict — *improved* or *not improved* — and carries on either way: a flat or "
                "negative result from an experiment is a result to read, not an error. It also keeps a **run history** "
                "for this session, one row per pass through Section 8, so an experiment can be compared with the default "
                "run (Section 10). One hundred abstracts from one "
                "seeded split of one corpus give no dispersion estimate; the delta is sample-sanity evidence that the "
                "adaptation contract works, not a benchmark, and a lower masked perplexity on paper abstracts says nothing "
                "about your corpus until you measure it there.\n\n"
                "**Predict before running:** how many points of masked perplexity will four adapted layers gain on the "
                "test abstracts — less than 1, about 2–3, or more than 5?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, mask_rate=MASK_RATE, seed=SEED)\n"
                "adapted_val = pipe.evaluate(val_records, mask_rate=MASK_RATE, seed=SEED)\n"
                "comparison = {{\n"
                "    metric: {{'unigram_floor': round(unigram[metric], 4), 'frozen': round(frozen_test[metric], 4), 'adapted': round(adapted_test[metric], 4)}}\n"
                "    for metric in ('perplexity', 'bits_per_token', 'top1_accuracy', 'top5_accuracy')\n"
                "}}\n"
                "comparison['delta_vs_frozen'] = {{metric: round(adapted_test[metric] - frozen_test[metric], 4) for metric in ('perplexity', 'bits_per_token', 'top1_accuracy', 'top5_accuracy')}}\n"
                "for metric, row in comparison.items():\n"
                "    print({{metric: row}})\n"
                "improved = adapted_test['perplexity'] < frozen_test['perplexity']\n"
                "verdict = 'improved: the adapted masked perplexity is below the frozen one' if improved else 'not improved: the adapted masked perplexity is not below the frozen one (read it; the notebook carries on)'\n"
                "print({{'verdict': verdict}})\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'trainable_layers': TRAINABLE_LAYERS, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'seed': SEED, 'trainable_parameters': adapt_result['n_trainable'], 'best_epoch': adapt_result['best_epoch'], 'frozen_perplexity': round(frozen_test['perplexity'], 3), 'adapted_perplexity': round(adapted_test['perplexity'], 3), 'delta': round(adapted_test['perplexity'] - frozen_test['perplexity'], 3)}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'layers':>6}} {{'epochs':>6}} {{'lr':>8}} {{'seed':>4}} {{'best':>4}} {{'frozen':>8}} {{'adapted':>8}} {{'delta':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['trainable_layers']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['seed']:>4}} {{h['best_epoch']:>4}} {{h['frozen_perplexity']:>8.3f}} {{h['adapted_perplexity']:>8.3f}} {{h['delta']:>7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'masking': {{'mask_rate': MASK_RATE, 'seed': SEED, 'n_masked_test': frozen_test['n_masked']}},\n"
                "    'baselines': {{'unigram_floor': unigram}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'verdict': verdict,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three rows of the comparison, the verdict, and how small the accuracy gains are "
                "next to the perplexity drop.\n\n"
                "<details><summary>Check your reasoning</summary>About 2–3 points. In the recorded runs of the previous "
                "notebook version the test masked perplexity fell from 15.09 to 12.59 in the local CPU pre-flight and to "
                "12.66 on the Kaggle T4 (top-1 53.3 → 54.8 % and 53.3 → 54.5 %). The small CPU/GPU difference comes from "
                "non-deterministic GPU arithmetic during training, not from an error. Perplexity moves more than top-1 "
                "accuracy because it also rewards giving the right token more probability when it is not the first "
                "choice. One hundred abstracts with no dispersion estimate cannot separate two configurations a few "
                "tenths of a point apart.</details>\n\n"
                "## 9. Clozes and embeddings before and after, export the adapter and reload it\n\n"
                "The clozes filled by the frozen model in Section 5 are filled again by the adapted model "
                "through the same `fill_mask` contract, printed side by side with the gold word and whether it appears in "
                "the top-`k` before and after; the two test abstracts are re-embedded and their cosine similarity and "
                "each vector's cosine to its frozen self are printed. Read these as observations: the adapter moves the "
                "last encoder layers, so **every embedding changes** — how much, and whether for the better on your "
                "similarity task, nothing here measures. The single-input `evaluation_report` helper — the inference-stage "
                "helper — is written for the first cloze and stays `not-measurable`, because one cloze has no metric.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the last four encoder layers, about 113 MB — as "
                "`adapter.safetensors`, with a `manifest.json` recording the artifact format, the base model id and "
                "revision, the digest of the base `model.safetensors`, the tensor names, the file size and SHA-256, the "
                "training configuration and the epoch history (OUT8). `BERTMaskedLMPipeline.from_artifact` re-verifies "
                "the base snapshot, checks the artifact manifest and digest **before** deserialising, refuses any tensor "
                "that is not an encoder-layer tensor of the base, and overlays the tensors onto a freshly loaded base — a "
                "new object from files, not the in-memory model (VER2). The cell checks for an identical test perplexity "
                "on ten records, identical candidates and identical embeddings (VER4), and stops with an explanation if "
                "they differ. Under BYOD the clozes are your test records, already scored in Sections 6 and 8, and are "
                "labelled that way, not as unseen text.\n\n"
                "**Predict before running:** will adaptation change the candidates of every cloze? Will each abstract's "
                "adapted embedding still be close to its frozen one?"
            ),
            "code": (
                "import csv\n"
                "import shutil\n\n"
                "rows = []\n"
                "for record in unseen_records:\n"
                "    text, gold_word = clozes[record['id']]\n"
                "    after = [c['token'] for c in pipe.fill_mask(text, top_k=TOP_K)['candidates']]\n"
                "    rows.append({{'id': record['id'], 'cloze': text, 'gold_word': gold_word, 'frozen_candidates': ' '.join(before[record['id']]), 'adapted_candidates': ' '.join(after), 'gold_in_top_k_frozen': gold_word in before[record['id']], 'gold_in_top_k_adapted': gold_word in after}})\n"
                "    print({{k: rows[-1][k] for k in ('id', 'gold_word', 'frozen_candidates', 'adapted_candidates', 'gold_in_top_k_frozen', 'gold_in_top_k_adapted')}})\n"
                "vectors_after = np.asarray(pipe.embed(pair_texts, pooling=POOLING)['embeddings'], dtype=np.float32)\n"
                "embedding_shift = {{'pair_cosine_frozen': round(float(vectors_before[0] @ vectors_before[1]), 4), 'pair_cosine_adapted': round(float(vectors_after[0] @ vectors_after[1]), 4), 'self_cosine_frozen_vs_adapted': [round(float(vectors_before[i] @ vectors_after[i]), 4) for i in range(2)]}}\n"
                "single_report = evaluation_report(pipe.fill_mask(cloze, top_k=TOP_K), [gold], sample_kind='one unseen SciTLDR abstract cloze' if not USE_BYOD else 'one BYOD test record (already scored in Sections 6 and 8; not unseen)')\n"
                "print({{'embedding_shift': embedding_shift, 'single_input_report_verdict': single_report['verdict'], 'clozes_with_changed_candidates': sum(r['frozen_candidates'] != r['adapted_candidates'] for r in rows), 'of': len(rows)}})\n"
                "with open('outputs/{stem}_cloze.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.DictWriter(handle, fieldnames=list(rows[0]))\n"
                "    writer.writeheader()\n"
                "    writer.writerows(rows)\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...'}})\n\n"
                "reloaded = BERTMaskedLMPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "parity_records = test_records[:10]\n"
                "ppl_pair = (pipe.evaluate(parity_records, mask_rate=MASK_RATE, seed=SEED)['perplexity'], reloaded.evaluate(parity_records, mask_rate=MASK_RATE, seed=SEED)['perplexity'])\n"
                "cand_pair = [(r['adapted_candidates'], ' '.join(c['token'] for c in reloaded.fill_mask(r['cloze'], top_k=TOP_K)['candidates'])) for r in rows]\n"
                "vectors_reloaded = np.asarray(reloaded.embed(pair_texts, pooling=POOLING)['embeddings'], dtype=np.float32)\n"
                "parity = {{'perplexity_in_memory': round(ppl_pair[0], 6), 'perplexity_reloaded': round(ppl_pair[1], 6), 'identical_candidates': sum(a == b for a, b in cand_pair), 'of': len(cand_pair), 'embeddings_identical': bool(np.array_equal(vectors_after, vectors_reloaded))}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "if not (abs(ppl_pair[0] - ppl_pair[1]) < 1e-6 and parity['identical_candidates'] == parity['of'] and parity['embeddings_identical']):\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the model that was evaluated in Section 8. Re-run from Section 7 (it reloads the pretrained model before adapting), or restart the session and choose Run all.')\n\n"
                "weight_entry = next(entry for entry in snapshot['files'] if entry['path'] == WEIGHT_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': len(snapshot['files']), 'total_bytes': snapshot.get('totalBytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': weight_entry['sha256']}},\n"
                "    'data_source': data_source,\n"
                "    'token_budget': token_budget,\n"
                "    'duplicate_texts_dropped': dropped_duplicates,\n"
                "    'cloze_source': cloze_source,\n"
                "    'corpus': {{'name': CORPUS_NAME, 'release': CORPUS_RELEASE, 'base_url': CORPUS_BASE_URL, 'files': {{k: {{'name': v[0], 'bytes': v[1], 'sha256': v[2]}} for k, v in CORPUS_FILES.items()}}, 'license': CORPUS_LICENSE}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'cloze': cloze, 'gold_word': gold, 'fill_mask': {{k: filled[k] for k in ('candidates', 'top_k', 'n_tokens')}}, 'embed': {{k: embedding_result[k] for k in ('dim', 'pooling', 'normalized', 'n_tokens')}}, 'seconds': {{'fill_mask': fill_seconds, 'embed': embed_seconds}}}},\n"
                "    'comparison': comparison,\n"
                "    'clozes_before_after': rows,\n"
                "    'embedding_shift': embedding_shift,\n"
                "    'single_input_report': single_report,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice:** which clozes changed their candidates, each vector's cosine to its frozen self, and the "
        "reload-parity line.\n\n"
        "<details><summary>Check your reasoning</summary>Not necessarily every cloze: in the local CPU pre-flight of the "
        "previous notebook version `problems` entered the first cloze's top five after adaptation, while the multi-piece "
        "gold words `foveation` and `normalization` matched neither before nor after (no single candidate can). The "
        "embeddings do all move, because the adapted layers are shared by every input, but only a little: each "
        "abstract's adapted vector had a cosine of about 0.94 to its frozen self. Whether that move helps a similarity "
        "task is not measured here. Reload parity was exact (identical ten-record perplexity, candidates and "
        "embeddings): the exported adapter is the model that was evaluated.</details>\n\n"
        "## 10. Your turn — change one thing: fewer trainable layers\n\n"
        "Optional; **Predict → Change → Run → Observe → Explain**. It retrains, so it takes about as long as Section 7 "
        "did.\n\n"
        "1. **Predict:** with only the last encoder layer trainable instead of four, will the test perplexity gain be "
        "about the same, about half, or close to zero? Write your guess down, next to the default run's numbers in the "
        "Section 8 run history.\n"
        "2. **Change:** in Section 7 set `TRAINABLE_LAYERS = 1`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained "
        "model before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run "
        "history, and Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation perplexity again (about 12.9, not the "
        "adapted 10.9); in Section 8, the run history now has two rows — compare `trainable_parameters` and `delta`; in "
        "Section 9, the adapter holds 16 tensors instead of 64 and reload parity still holds.\n"
        "5. **Explain:** in one sentence, why does training fewer layers change the gain the way it did?\n\n"
        "<details><summary>Check your reasoning</summary>About two thirds of the gain: not all of it, and not zero. "
        "In a local Windows CPU check of this notebook version (float32, real weights, default settings otherwise) "
        "the default run gave 15.09 → 12.59 (delta −2.50) with four layers, and the one-layer re-run gave 15.09 → "
        "13.36 (delta −1.73); its epoch 0 showed the frozen validation perplexity 12.89, validation perplexity went "
        "12.89 → 11.77 → 11.45, the adapter held 16 tensors (28.4 MB instead of 113 MB) and reload parity was exact. "
        "One layer has a quarter of the trainable parameters (7,087,872 of 109,514,298) and can only re-weight the "
        "last layer's view of the text, so it adapts less to the new domain in the same number of steps; that the "
        "last layer alone still gives most of the gain suggests much of the domain shift is in how the final layer "
        "maps context to words. If your gain did not shrink, check that epoch 0 showed the frozen validation "
        "perplexity; if it did not, the model was not reset (restart and **Run all**).</details>\n\n"
        "## Interpretation and limits\n\n"
        "The frozen encoder already predicts the masked words of paper abstracts far better than a unigram model does "
        "(a masked perplexity near 15 against a floor in the thousands, top-1 accuracy above 50 % against a few percent "
        "— BooksCorpus and Wikipedia contain technical prose), and a bounded continuation of its own pre-training "
        "objective on 300 abstracts, touching only the last four encoder layers, lowers held-out masked perplexity by "
        "about 2.5 points (15.09 → 12.59 in the local CPU pre-flight of the previous notebook version, 15.09 → 12.66 on "
        "its Kaggle T4 run), with a 113 MB adapter that reloads to identical likelihoods, candidates "
        "and embeddings. That is the claim: the adaptation contract can continue pre-training end to end on a real "
        "corpus, and the number it produces is read against the frozen model and a context-free floor rather than in "
        "isolation.\n\n"
        "Masked perplexity is intrinsic: it says how well the encoder predicts missing tokens of text it did not write, "
        "at one seeded 15 % masking of one seeded split of one corpus with no dispersion estimate. It is not embedding "
        "quality, retrieval performance or downstream accuracy, and a lower value does not make the candidates or the "
        "cosine table in Section 9 better — those are observations. The adapter changes the last layers, which every "
        "input shares, so every embedding shifts (Section 9 prints each vector's cosine to its frozen self) and the "
        "fill-mask `score` stays a softmax ranking signal, not a probability. Text is lower-cased and accent-stripped by "
        "the tokenizer; texts over 512 WordPiece tokens are rejected everywhere, never truncated; the checkpoint carries "
        "the gender and occupation associations the upstream card documents, and continued pre-training on a corpus does "
        "not remove them.\n\n"
        "Three things to carry to real data. **Floors first:** the unigram floor and the frozen masked perplexity on "
        "*your* held-out documents are the numbers to read before any adapted one. **Leakage:** de-duplicate texts "
        "across splits (the contract does this case-insensitively) and split by document collection or author when your "
        "documents come from one. **Downstream:** a better masked perplexity on your domain is a reason to *measure* "
        "your similarity or classification task with the adapted encoder, not evidence that it improved.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify a real corpus, validate "
        "the demonstrated dataset contract without leakage, execute both inference contracts and a bounded continued "
        "pre-training, evaluate by masked-token metrics against a trivial floor and the frozen model on an independent "
        "split, and emit the shown machine-readable artifacts — without the repository being reachable. It does **not** "
        "establish benchmark superiority, embedding or cloze quality on any domain, a usable acceptance threshold, or "
        "production fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one form field; note the "
        "numbers you want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run "
        "after** runs the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model "
        "before they use it, so no experiment inherits an earlier adaptation.\n\n"
        "- **Fewer trainable layers:** Section 10.\n"
        "- **More epochs:** set `EPOCHS = 4` in Section 7, select Section 7 and choose **Run after**; watch whether "
        "validation perplexity keeps falling or turns (the best epoch is kept either way).\n"
        "- **Other masks:** change `SEED` in Section 6, select Section 6 and choose **Run after**; read how much the "
        "frozen and adapted metrics move with a different set of masked positions.\n"
        "- **Other pooling:** switch `POOLING` in Section 5, select Section 5 and choose **Run after**; re-read the "
        "pair cosine and the cosine shift in Section 9.\n"
        "- **Your own documents:** BYOD (Section 4, then **Run after**); read the unigram floor and the frozen "
        "perplexity before the adapted number.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux "
        "wheels. Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or "
        "\"does not match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook "
        "from the repository.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory. Restart the "
        "session and choose **Run all**; on CPU, close other notebooks first.\n"
        "- **Out of disk, or the checkpoint download stops.** The locked install and the 440 MB checkpoint need a few "
        "GB of free space. Start a fresh runtime, or delete `dimer_isolated_env/` and `weights/` from an earlier "
        "attempt.\n"
        "- **A digest or size mismatch in Section 3 or 4.** A download was incomplete or altered; the notebook refuses "
        "it rather than continuing. Run the cell again; never edit the manifest or the corpus digests.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split left with too few documents (a "
        "corpus needs at least 12 distinct documents), a record over the 512-token ceiling (by split and id: split the "
        "document by paragraph), no test record with a usable opening sentence for the clozes, a missing column or a "
        "duplicate id. Fix the file and run Section 4 with **Run after** again. An empty or cancelled upload asks you "
        "to choose a file or set `BYOD_PATH`.\n"
        "- **Section 8 says \"not improved\".** Not an error: the adapted model did not beat the frozen one under "
        "these settings. Read the epoch history in Section 7; the export and reload in Section 9 still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded runs.** GPU training is not bit-for-bit deterministic: a tenth "
        "of a perplexity point between a T4 and a CPU run is expected. Larger differences on the default settings mean "
        "a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **`[MASK]` / cloze:** the special token that hides a word, and a sentence with one word hidden for the "
        "model to fill.\n"
        "- **WordPiece:** BERT's tokenizer; it splits rare words into several pieces, so one word can be several "
        "tokens.\n"
        "- **Softmax score:** the model's scores over all 30,522 tokens turned into numbers that sum to one; a ranking "
        "signal, not a calibrated probability of being right.\n"
        "- **Masked perplexity:** the exponential of the average negative log-likelihood of the hidden tokens; lower "
        "is better, and a value of *k* means the model is on average as unsure as a uniform choice among *k* tokens.\n"
        "- **Bits per masked token:** the same average expressed in bits.\n"
        "- **Top-1 / top-5 accuracy:** the share of hidden tokens that are the model's first choice / among its first "
        "five.\n"
        "- **Unigram floor:** a model that predicts every hidden token from word frequencies alone, ignoring the "
        "context; the score any useful model must beat.\n"
        "- **Continued pre-training:** further training on the model's own masked-word objective, with a new domain's "
        "unlabelled text.\n"
        "- **Trainable layers:** the encoder layers whose weights training may change; the rest stay frozen.\n"
        "- **Epoch / validation selection:** one pass over the training documents; the epoch kept is the one with the "
        "lowest validation perplexity.\n"
        "- **Training / validation / test split:** documents used to train, to choose the epoch, and to report the "
        "final result once.\n"
        "- **Embedding / pooling / cosine:** a fixed-length vector for a text, how the per-token vectors are combined "
        "into it (`cls` or `mean`), and the similarity of two unit vectors (1 = same direction).\n"
        "- **Adapter / reload parity:** the saved trained layers, and the check that a pipeline rebuilt from them gives "
        "the same perplexity, candidates and embeddings.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- On these test abstracts the unigram floor reached a masked perplexity of ___, the pretrained model ___ and "
        "the adapted model ___; the verdict was ___.\n"
        "- Adapting ___ layer(s) changed the perplexity by ___; with ___ layer(s) (Section 10) it changed by ___, "
        "because ___.\n"
        "- A lower masked perplexity tells me ___, but it does not tell me ___.\n"
        "- Before trusting this adaptation on my own documents I would measure ___ on ___.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/bert-masked-lm-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/bert-masked-lm-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/bert-masked-lm-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/google-research/bert\n"
        "- BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding (Devlin et al., NAACL 2019): https://arxiv.org/abs/1810.04805\n"
        "- TLDR: Extreme Summarization of Scientific Documents (Cachola et al., EMNLP Findings 2020; SciTLDR, Apache-2.0): https://arxiv.org/abs/2004.15011\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
